# Fix 1: Update backend/nixpacks.toml

[phases.setup]
nixPkgs = ["python311", "postgresql_15"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
  "python -m compileall -b .",
  "find . -name '*.py' -delete || true",
  "find . -name '__pycache__' -exec rm -rf {} + || true"
]

[start]
# Fixed: Use correct module path and set working directory
cmd = "cd /app && gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120 --access-logfile - --error-logfile -"

[variables]
PYTHONPATH = "/app:/app/backend"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
